
spring:
  mail:
    host: smtp.gmail.com
    username: roushank559@gmail.com
    password: tgjxgidqdimkwasi
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true